#How many souls are players worth when killed?
#Range: 1 ~ 20000
playerSouls = 2500
#How many souls are villagers worth when killed?
#Range: 1 ~ 20000
villagerSouls = 250
#How many souls are enemy faction members worth when killed?
#Range: 1 ~ 20000
factionSouls = 250
#How many souls are mobs worth when killed?
#Range: 1 ~ 20000
mobSouls = 150
#How many souls are animals worth when killed?
#Range: 1 ~ 20000
animalSouls = 100
#How many souls are undead worth when killed?
#Range: 1 ~ 20000
undeadSouls = 50

#Mana and Artifice // General Options
[ma_general_options]
	#Rituals of Aurora and Eventide by default will change time gradually for a prettier effect.  However this isn't without its performance impacts, and this can be toggled off by setting this to false, making the transition instant like the /time set commands. [true / false]
	gradualTimeChange = true
	#A comma separated list of entity IDs that the warding candle should ignore, regardless of detection (use this if it's stopping you from something you think it shouldn't; this isn't to expand what it will block)
	wardingCandleBlacklist = ""
	#A comma separated list of entity IDs that the warding candle should block (in addition to what it blocks by default); use this to expand what it will block.  Note that blacklist overrides this, so an entry in both will be blacklisted.
	wardingCandleWhitelist = ""
	#Change this to determine how many of a tier's tasks need to be completed before tiering up is allowed.  It is a percentage of the total tasks in the tier.  If you set this above 1, you cannot tier up through normal gameplay.  Use with caution.
	#Range: 0.01 ~ 2.0
	tierCompletePct = 0.8
	#What the mod considers 'melee distance' between two entities when one attacks the other.  This value is squared, so if you want 8 blocks put 64 in this config.
	#Range: 1.0 ~ 4096.0
	meleeDistance = 64.0
	#What the mod considers to be the average manaweave cost when generating manaweaves automatically for the player.
	#Range: 0 ~ 500
	averageManaweaveCost = 25
	#Comma separated list of dimension ids that spells can't be cast in.
	spellDimensionBlacklist = ""
	#Comma separated list of biome ids that spells can't be cast in.
	spellBiomeBlacklist = ""
	#How much damage does the fortification effect set all damage to
	#Range: 1.0 ~ 20.0
	fortificationDamageAmount = 4.0
	#How many kills does it take to fill up a crystal phylactery
	#Range: 1 ~ 1000
	phylacteryKills = 100
	#Can bosses be summoned?
	bossSummons = false
	#Can bosses be captured in phylacteries?
	bossPhylacteries = false
	#If true, the Ritual of Arcana will instantly rote spells upon completion, in addition to giving you the spell..
	liteMode = false
	#Set this to true to disable new villager profession registration.  This allows compatibility with Bukkit.  Note that you'll need to ensure the Codex Arcana is obtainable through different means!
	disableNewProfessions = false
	#Should summons be able to be right clicked with items to interact?  For example, shearing sheep or milking cows that have been summoned.
	summonInteractions = true

#Mana and Artifice // Villager Modification
[ma_villager_modification]
	#Adjust librarian villagers to not have enchanted books until tier 3.  This is done for balancing and to remove the exploit of rolling librarians for cheap enchants. [true / false]
	modifyVillagerTrades = true

#Raids are incremented when you use items/spells from the other factions.  When they get angry enough, you will be raided.
[ma_faction_raids]
	#Adjust the base amount per day that the chance to be raided goes up for each player.  This has no effect if classic raids are disabled.
	#Range: 0.0 ~ 1.0
	raidBaselineIncrease = 0.05
	#Adjust the amount per day that the chance to be raided goes up for each player based on their tier above 3 (this value * (tier-3)).  This is added to the baseline.  This has no effect if classic raids are disabled.
	#Range: 0.0 ~ 1.0
	raidTierIncrease = 0.05
	#How many attempts (within a 20x20x5 box centered on the player in question) should the game make to spawn a raid?  Note this will be re-attempted every 100 ticks until a successful spawn is made.  If you're lagging due to raid spawn attempts, lower this setting.
	#Range: 1 ~ 1000
	raidSpawnAttempts = 100
	#Should classic raiding be enabled?  Raids are based on a chance value.  The value is increased each day there is not a raid.  If the chance hits a total of 1.0 or greater, it's a guaranteed raid.  The chance resets after a raid successfully spawns.
	classicRaids = false

#Mana and Artifice // Worldgen Options
[ma_worldgen_options]
	#How far apart wellspring nodes must be as a minimum.  They can be farther than this depending on world seed and generation.
	#Range: 100 ~ 15000
	wellspringDistance = 500
	#If true, total wellspring power will be calculated per faction rather than per player.
	wellspringFactionClaims = false
	#If true, wellsprings will generate with no affinity and the type of lens used will set the affinity of the node.
	genericWellsprings = false
	#Size of vinteum veins
	#Range: 1 ~ 20
	vinteumVeinSize = 9
	#Count of vinteum veins
	#Range: 1 ~ 100
	vinteumVeinCount = 20
	#Max Y-value of vinteum veins
	#Range: 10 ~ 255
	vinteumVeinYValue = 63

#Mana and Artifice // Artifact Options
[ma_artifact_options]
	#By default meteor jump will follow the mobGriefing rule.  Set this to true to override that regardless of the game rule.
	meteorJumpDestruction = true
	#How many reflect charges the Spellweaver armor set has
	#Range: 0 ~ 99
	councilArmorReflectCharges = 3
	#How many ticks the Spellweaver armor set needs to regenerate one reflect charge
	#Range: 20 ~ 2000
	councilArmorReflectRecharge = 100
	#The percent chance the fey armor will reflect projectiles.
	#Range: 0.0 ~ 1.0
	feyArmorReflectChance = 0.20000000298023224
	#The percent chance the fey armor will randomly teleport melee attackers.
	#Range: 0.0 ~ 1.0
	feyArmorTeleportChance = 0.20000000298023224

